### ISSUE TITLE
Can this be used on iOS?

### ISSUE THREAD

**Issue by adamjuls** [w-ensink/basic_pitch#1]
Hi! Thank you for making this open source. Do you know if this can be used on iOS?

**Comment by w-ensink** [comment]
Hi, yes this should be working on iOS now (and macOS as well). I haven't updated the readme yet, but I managed to build it on my iPhone and a Simulator. You might have to link agains the C++ standard library tho, which you can do by adding `-lc++` to `Build Settings -> Other Linker Flags` in Xcode. 

Let me know if this works. A PR with an update to the readme would also be appreciated if you manage to get it working :-)

**Comment by adamjuls** [comment]
I'm a new software developer to iOS, especially with adding new complex libraries like this. Can you point me to a direction where I can read up or study how to build this on an iOS app?

**Comment by w-ensink** [comment]
This library is intended to be used in Rust projects, so it's not very suitable to use in an iOS project where you primarily program in Swift or Objective-C. It's only really useful if you have the processing part of your app written in Rust. If that's not the case then I'd recommend looking at the C++ (`/cpp`) part of this repository and figure out how to build a C++ library from it, because that interoperates much more smoothly with Swift and Objective-C (via Obj-C++).
